language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - py.test
notifications:
  email:
    recipients:
      - dev@picwell.com
cache:
  - directories:
      # If travis' cache breaks, they may have updated python
      - /home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages
sudo: false
