language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - py.test
notifications:
  email:
    recipients:
      - dev@picwell.com
cache:
  - pip
sudo: false
